POST http://localhost:3001/api/notes
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwN2VmNTQ0NjUwZDljM2JhYzlkYTMyOCIsInVzZXJuYW1lIjoibWFkZXZhbCIsImlhdCI6MTYxODk0MzMyMn0.bL8WTxaTl5r4A9f04mEXlIJdPSSn46qcNNw0KcKl11U

{
    "content": "Probando la relacion entre colecciones",
    "important": false
}